[package]
name = "teifs-s3"
description = "The S3 API over a TeiFS store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
teifs-store.workspace = true
teifs-iam.workspace = true
teifs-policy.workspace = true
teifs-types.workspace = true
teifs-notify.workspace = true
teifs-crypto.workspace = true
zeroize.workspace = true
serde.workspace = true
form_urlencoded.workspace = true
percent-encoding.workspace = true
s3s.workspace = true
s3s-multipart.workspace = true
async-trait.workspace = true
tokio.workspace = true
tokio-util.workspace = true
futures.workspace = true
bytes.workspace = true
base64.workspace = true
serde_json.workspace = true
time.workspace = true
serde-saphyr.workspace = true
reqwest.workspace = true
uuid.workspace = true
aws-lc-rs.workspace = true
aws-sdk-s3.workspace = true
http = "1"
http-body = "1"
mime = "0.3"
hyper.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
http-body-util.workspace = true
ipnet.workspace = true
prometheus-client.workspace = true
fs4.workspace = true
arrow-array.workspace = true
arrow-schema.workspace = true
flate2.workspace = true
orc-rust.workspace = true
parquet.workspace = true
md-5.workspace = true
zip.workspace = true
sysinfo.workspace = true
x509-parser.workspace = true
xxhash-rust.workspace = true

[target.'cfg(unix)'.dependencies]
pprof.workspace = true

[dev-dependencies]
proptest.workspace = true
rcgen.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
