doc-valid-idents = ["TeiFS", "ETag", "ETags", "MinIO", "APFS", "Btrfs", "XFS", "NTFS", "CRC32", "CRC32C", "CRC64NVME", "SHA-1", "SHA-256", "..", "S3", "OpenBao", "OpenID", "HAProxy", "UUIDv7", "AES-256-GCM", "HKDF-SHA256", "HMAC-SHA256"]
allow-unwrap-in-tests = true
allow-print-in-tests = true
