# Generated by `cargo xtask manifests` for TeiFS 1.2.3.
class Teifs < Formula
  desc "S3-compatible server and client for your folders"
  homepage "https://github.com/teispace/teifs"
  version "1.2.3"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    url "https://github.com/teispace/teifs/releases/download/v1.2.3/teifs-1.2.3-universal-apple-darwin.tar.gz"
    sha256 "4444444444444444444444444444444444444444444444444444444444444444"
  end

  on_linux do
    on_intel do
      url "https://github.com/teispace/teifs/releases/download/v1.2.3/teifs-1.2.3-x86_64-unknown-linux-musl.tar.gz"
      sha256 "7777777777777777777777777777777777777777777777777777777777777777"
    end
    on_arm do
      url "https://github.com/teispace/teifs/releases/download/v1.2.3/teifs-1.2.3-aarch64-unknown-linux-musl.tar.gz"
      sha256 "3333333333333333333333333333333333333333333333333333333333333333"
    end
  end

  def install
    bin.install "teifs"
    generate_completions_from_executable(bin/"teifs", "completions")
  end

  service do
    run [opt_bin/"teifs", "serve", var/"teifs"]
    keep_alive true
    log_path var/"log/teifs.log"
    error_log_path var/"log/teifs.log"
  end

  test do
    assert_equal "teifs 1.2.3", shell_output("#{bin}/teifs --version").strip
  end
end
