//! `manifests VERSION SHA256SUMS OUT`: the Homebrew formula (`OUT/teifs.rb`) and the
//! winget manifests (`OUT/winget/`) of a release, from its checksums. The release
//! workflow attaches both to the draft; submitting them is the maintainer's.

use std::{fs, path::Path};

const REPO: &str = "https://github.com/teispace/teifs";
const DESCRIPTION: &str =
    "Your folders as a drive and as S3: an S3-compatible server and client in one binary.";
const WINGET_ID: &str = "Teispace.TeiFS";
const WINGET_SCHEMA: &str = "1.10.0";

/// `cargo xtask manifests VERSION SHA256SUMS OUT`.
pub fn write(version: &str, sums: &Path, out: &Path) -> Result<(), String> {
    let sums =
        fs::read_to_string(sums).map_err(|e| format!("can't read {}: {e}", sums.display()))?;
    let winget = out.join("winget");
    fs::create_dir_all(&winget).map_err(|e| format!("can't create {}: {e}", winget.display()))?;
    let mut files = vec![(out.join("teifs.rb"), homebrew(version, &sums)?)];
    for (name, text) in self::winget(version, &sums)? {
        files.push((winget.join(name), text));
    }
    for (path, text) in files {
        fs::write(&path, text).map_err(|e| format!("can't write {}: {e}", path.display()))?;
        println!("manifests: {}", path.display());
    }
    Ok(())
}

/// The archive of `target` and its SHA-256, as `SHA256SUMS.txt` lists it.
fn archive(version: &str, sums: &str, target: &str, extension: &str) -> Result<Archive, String> {
    let name = format!("teifs-{version}-{target}.{extension}");
    let sha256 = sums
        .lines()
        .find_map(|line| {
            let (hash, file) = line.split_once(char::is_whitespace)?;
            // `sha256sum` marks binary mode with `*`.
            (file.trim_start().trim_start_matches('*') == name).then_some(hash)
        })
        .ok_or_else(|| format!("SHA256SUMS has no {name}"))?;
    if sha256.len() != 64 || !sha256.bytes().all(|b| b.is_ascii_hexdigit()) {
        return Err(format!("SHA256SUMS has no valid SHA-256 for {name}"));
    }
    Ok(Archive {
        url: format!("{REPO}/releases/download/v{version}/{name}"),
        folder: format!("teifs-{version}-{target}"),
        sha256: sha256.to_ascii_lowercase(),
    })
}

struct Archive {
    url: String,
    folder: String,
    sha256: String,
}

/// A formula for a tap: the release's binaries (macOS universal, Linux static), shell
/// completions and a `brew services` service.
fn homebrew(version: &str, sums: &str) -> Result<String, String> {
    let mac = archive(version, sums, "universal-apple-darwin", "tar.gz")?;
    let intel = archive(version, sums, "x86_64-unknown-linux-musl", "tar.gz")?;
    let arm = archive(version, sums, "aarch64-unknown-linux-musl", "tar.gz")?;
    Ok(format!(
        r##"# Generated by `cargo xtask manifests` for TeiFS {version}.
class Teifs < Formula
  desc "S3-compatible server and client for your folders"
  homepage "{REPO}"
  version "{version}"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    url "{mac_url}"
    sha256 "{mac_sha}"
  end

  on_linux do
    on_intel do
      url "{intel_url}"
      sha256 "{intel_sha}"
    end
    on_arm do
      url "{arm_url}"
      sha256 "{arm_sha}"
    end
  end

  def install
    bin.install "teifs"
    generate_completions_from_executable(bin/"teifs", "completions")
  end

  service do
    run [opt_bin/"teifs", "serve", var/"teifs"]
    keep_alive true
    log_path var/"log/teifs.log"
    error_log_path var/"log/teifs.log"
  end

  test do
    assert_equal "teifs {version}", shell_output("#{{bin}}/teifs --version").strip
  end
end
"##,
        mac_url = mac.url,
        mac_sha = mac.sha256,
        intel_url = intel.url,
        intel_sha = intel.sha256,
        arm_url = arm.url,
        arm_sha = arm.sha256,
    ))
}

/// The three manifests of a winget package version: the zip of each Windows build,
/// with `teifs.exe` inside as a portable command.
fn winget(version: &str, sums: &str) -> Result<Vec<(String, String)>, String> {
    let header = |kind: &str| {
        format!(
            "# Generated by `cargo xtask manifests` for TeiFS {version}.\n\
             # yaml-language-server: $schema=https://aka.ms/winget-manifest.{kind}.{WINGET_SCHEMA}.schema.json\n\n\
             PackageIdentifier: {WINGET_ID}\nPackageVersion: {version}\n"
        )
    };
    let footer = |kind: &str| format!("ManifestType: {kind}\nManifestVersion: {WINGET_SCHEMA}\n");

    let installers = [
        ("x64", "x86_64-pc-windows-msvc"),
        ("arm64", "aarch64-pc-windows-msvc"),
    ]
    .into_iter()
    .map(|(architecture, target)| {
        let zip = archive(version, sums, target, "zip")?;
        Ok(format!(
            "  - Architecture: {architecture}\n    \
             InstallerUrl: {url}\n    \
             InstallerSha256: {sha}\n    \
             NestedInstallerFiles:\n      \
             - RelativeFilePath: {folder}\\teifs.exe\n        \
             PortableCommandAlias: teifs\n",
            url = zip.url,
            sha = zip.sha256.to_ascii_uppercase(),
            folder = zip.folder,
        ))
    })
    .collect::<Result<String, String>>()?;
    let version_manifest = format!(
        "{}DefaultLocale: en-US\n{}",
        header("version"),
        footer("version")
    );
    let installer = format!(
        "{}InstallerType: zip\nNestedInstallerType: portable\nCommands:\n  - teifs\n\
         Installers:\n{installers}{}",
        header("installer"),
        footer("installer")
    );
    let locale = format!(
        "{}PackageLocale: en-US\nPublisher: Teispace\nPublisherUrl: https://github.com/teispace\n\
         PublisherSupportUrl: {REPO}/issues\nPackageName: TeiFS\nPackageUrl: {REPO}\n\
         License: MIT OR Apache-2.0\nLicenseUrl: {REPO}/blob/main/LICENSE-MIT\n\
         ShortDescription: '{DESCRIPTION}'\n\
         Tags:\n  - s3\n  - object-storage\n  - storage\n  - server\n\
         ReleaseNotesUrl: {REPO}/releases/tag/v{version}\n{}",
        header("defaultLocale"),
        footer("defaultLocale")
    );
    Ok(vec![
        (format!("{WINGET_ID}.yaml"), version_manifest),
        (format!("{WINGET_ID}.installer.yaml"), installer),
        (format!("{WINGET_ID}.locale.en-US.yaml"), locale),
    ])
}

#[cfg(test)]
mod tests {
    use super::*;

    const SUMS: &str = include_str!("../fixtures/SHA256SUMS.txt");

    #[test]
    fn the_formula_is_the_fixture() {
        assert_eq!(
            homebrew("1.2.3", SUMS).unwrap(),
            include_str!("../fixtures/teifs.rb")
        );
    }

    #[test]
    fn the_winget_manifests_are_the_fixtures() {
        let manifests = winget("1.2.3", SUMS).unwrap();
        let expected = [
            (
                "Teispace.TeiFS.yaml",
                include_str!("../fixtures/winget/Teispace.TeiFS.yaml"),
            ),
            (
                "Teispace.TeiFS.installer.yaml",
                include_str!("../fixtures/winget/Teispace.TeiFS.installer.yaml"),
            ),
            (
                "Teispace.TeiFS.locale.en-US.yaml",
                include_str!("../fixtures/winget/Teispace.TeiFS.locale.en-US.yaml"),
            ),
        ];
        assert_eq!(manifests.len(), expected.len());
        for ((name, text), (want_name, want)) in manifests.iter().zip(expected) {
            assert_eq!(name, want_name);
            assert_eq!(text, want, "{name}");
        }
    }

    #[test]
    fn checksums_are_found_exactly() {
        // `*name` (binary mode) is read, a longer name with the same start isn't taken,
        // and a missing or malformed checksum is refused.
        let a = "a".repeat(64);
        let sums = format!(
            "{a}  teifs-1.0.0-x86_64-pc-windows-msvc.zip.sig\n{}  *teifs-1.0.0-x86_64-pc-windows-msvc.zip\n",
            "B".repeat(64)
        );
        let zip = archive("1.0.0", &sums, "x86_64-pc-windows-msvc", "zip").unwrap();
        assert_eq!(zip.sha256, "b".repeat(64));
        assert_eq!(zip.folder, "teifs-1.0.0-x86_64-pc-windows-msvc");
        assert_eq!(
            zip.url,
            "https://github.com/teispace/teifs/releases/download/v1.0.0/teifs-1.0.0-x86_64-pc-windows-msvc.zip"
        );
        assert!(archive("1.0.0", &sums, "aarch64-pc-windows-msvc", "zip").is_err());
        let short = "abc  teifs-1.0.0-x86_64-pc-windows-msvc.zip\n";
        assert!(archive("1.0.0", short, "x86_64-pc-windows-msvc", "zip").is_err());
        let not_hex = format!(
            "{}  teifs-1.0.0-x86_64-pc-windows-msvc.zip\n",
            "g".repeat(64)
        );
        assert!(archive("1.0.0", &not_hex, "x86_64-pc-windows-msvc", "zip").is_err());
    }
}
