[package]
name = "teifs"
description = "TeiFS: S3 for your own disks"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[[bin]]
name = "teifs"
path = "src/main.rs"

[dependencies]
teifs-store.workspace = true
teifs-server.workspace = true
tokio.workspace = true
clap.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
